# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        # only protect the truly private URLs:
        - { path: ^/dashboard,             roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin,                 roles: ROLE_ADMIN }
        - { path: ^/document/new,          roles: [ROLE_ADMIN, ROLE_MANAGER] }
        - { path: ^/document/\d+/edit,     roles: [ROLE_ADMIN, ROLE_MANAGER] }
        - { path: ^/document/\d+/delete,   roles: [ROLE_ADMIN, ROLE_MANAGER] }
        - { path: ^/document/\d+/logs,     roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/document,              roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/announcement/new,      roles: [ROLE_ADMIN, ROLE_MANAGER] }
        - { path: ^/announcement/\d+/edit, roles: [ROLE_ADMIN, ROLE_MANAGER] }
        - { path: ^/announcement/\d+/delete,roles: [ROLE_ADMIN, ROLE_MANAGER] }
        - { path: ^/announcement,          roles: IS_AUTHENTICATED_FULLY }

# test‐env override stays the same
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
