security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                # target: app_any_route

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:

        - { path: ^/document/new,      roles: [ROLE_ADMIN, ROLE_MANAGER] }
        - { path: ^/document/\d+/edit, roles: [ROLE_ADMIN, ROLE_MANAGER] }
        - { path: ^/document/\d+/delete, roles: [ROLE_ADMIN, ROLE_MANAGER] }


        - { path: ^/document, roles: IS_AUTHENTICATED_FULLY }


        - { path: ^/document/\d+/logs, roles: IS_AUTHENTICATED_FULLY }


        - { path: ^/admin,                        roles: ROLE_ADMIN }


        - { path: ^/announcement/new,             roles: [ROLE_ADMIN,ROLE_MANAGER] }
        - { path: ^/announcement/\d+/edit,        roles: [ROLE_ADMIN,ROLE_MANAGER] }
        - { path: ^/announcement/\d+/delete,      roles: [ROLE_ADMIN,ROLE_MANAGER] }
        - { path: ^/announcement,                 roles: IS_AUTHENTICATED_FULLY }




        - { path: ^/dashboard,                    roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/jobs,                         roles: IS_AUTHENTICATED_ANONYMOUSLY }



when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
