<?php

namespace ContainerOSYt0t5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fmc9k7cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fmc9k7c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fmc9k7c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'announcement' => ['privates', '.errored..service_locator.Fmc9k7c.App\\Entity\\Announcement', NULL, 'Cannot autowire service ".service_locator.Fmc9k7c": it needs an instance of "App\\Entity\\Announcement" but this type has been excluded in "config/services.yaml".'],
            'announcementRepository' => ['privates', 'App\\Repository\\AnnouncementRepository', 'getAnnouncementRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'announcement' => 'App\\Entity\\Announcement',
            'announcementRepository' => 'App\\Repository\\AnnouncementRepository',
            'entityManager' => '?',
        ]);
    }
}
