<?php

namespace ContainerOSYt0t5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2BrnKx3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2BrnKx3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2BrnKx3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'calendarEntry' => ['privates', '.errored..service_locator.2BrnKx3.App\\Entity\\CalendarEntry', NULL, 'Cannot autowire service ".service_locator.2BrnKx3": it needs an instance of "App\\Entity\\CalendarEntry" but this type has been excluded in "config/services.yaml".'],
        ], [
            'calendarEntry' => 'App\\Entity\\CalendarEntry',
        ]);
    }
}
