<?php

namespace ContainerOSYt0t5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnouncement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q.wNFcx.App\Entity\Announcement' shared service.
     *
     * @return \App\Entity\Announcement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.q.wNFcx": it needs an instance of "App\\Entity\\Announcement" but this type has been excluded in "config/services.yaml".');
    }
}
