<?php

namespace ContainerOSYt0t5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBirthdayAnnouncementsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\BirthdayAnnouncementsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\BirthdayAnnouncementsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:birthday-announcements', [], 'Create an announcement for each user whose birthday is today', false, #[\Closure(name: 'App\\Command\\BirthdayAnnouncementsCommand')] fn (): \App\Command\BirthdayAnnouncementsCommand => ($container->privates['App\\Command\\BirthdayAnnouncementsCommand'] ?? $container->load('getBirthdayAnnouncementsCommandService')));
    }
}
