<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'announcements' => [parent::class, 'announcements', null, 16],
        "\0".parent::class."\0".'birthday' => [parent::class, 'birthday', null, 16],
        "\0".parent::class."\0".'calendarEntries' => [parent::class, 'calendarEntries', null, 16],
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'enabled' => [parent::class, 'enabled', null, 16],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'tags' => [parent::class, 'tags', null, 16],
        'announcements' => [parent::class, 'announcements', null, 16],
        'birthday' => [parent::class, 'birthday', null, 16],
        'calendarEntries' => [parent::class, 'calendarEntries', null, 16],
        'comments' => [parent::class, 'comments', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'enabled' => [parent::class, 'enabled', null, 16],
        'firstName' => [parent::class, 'firstName', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'tags' => [parent::class, 'tags', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
