<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Announcement extends \App\Entity\Announcement implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null, 16],
        "\0".parent::class."\0".'commentsEnabled' => [parent::class, 'commentsEnabled', null, 16],
        "\0".parent::class."\0".'content' => [parent::class, 'content', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imagePath' => [parent::class, 'imagePath', null, 16],
        "\0".parent::class."\0".'infoboard' => [parent::class, 'infoboard', null, 16],
        "\0".parent::class."\0".'isPublic' => [parent::class, 'isPublic', null, 16],
        "\0".parent::class."\0".'sender' => [parent::class, 'sender', null, 16],
        "\0".parent::class."\0".'targetRoles' => [parent::class, 'targetRoles', null, 16],
        "\0".parent::class."\0".'targetTags' => [parent::class, 'targetTags', null, 16],
        "\0".parent::class."\0".'targetUsers' => [parent::class, 'targetUsers', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'visible' => [parent::class, 'visible', null, 16],
        'comments' => [parent::class, 'comments', null, 16],
        'commentsEnabled' => [parent::class, 'commentsEnabled', null, 16],
        'content' => [parent::class, 'content', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imagePath' => [parent::class, 'imagePath', null, 16],
        'infoboard' => [parent::class, 'infoboard', null, 16],
        'isPublic' => [parent::class, 'isPublic', null, 16],
        'sender' => [parent::class, 'sender', null, 16],
        'targetRoles' => [parent::class, 'targetRoles', null, 16],
        'targetTags' => [parent::class, 'targetTags', null, 16],
        'targetUsers' => [parent::class, 'targetUsers', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'visible' => [parent::class, 'visible', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
