<?php

namespace ContainerYXB2xY0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NRko3pHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nRko3pH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nRko3pH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::editUser' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\AdminController::manage' => ['privates', '.service_locator.bYqs9Eo', 'get_ServiceLocator_BYqs9EoService', true],
            'App\\Controller\\AdminController::register' => ['privates', '.service_locator.t8346QO', 'get_ServiceLocator_T8346QOService', true],
            'App\\Controller\\AnnouncementController::delete' => ['privates', '.service_locator.q.wNFcx', 'get_ServiceLocator_Q_WNFcxService', true],
            'App\\Controller\\AnnouncementController::edit' => ['privates', '.service_locator.q.wNFcx', 'get_ServiceLocator_Q_WNFcxService', true],
            'App\\Controller\\AnnouncementController::index' => ['privates', '.service_locator.AiNvJdq', 'get_ServiceLocator_AiNvJdqService', true],
            'App\\Controller\\AnnouncementController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AnnouncementController::show' => ['privates', '.service_locator.Fmc9k7c', 'get_ServiceLocator_Fmc9k7cService', true],
            'App\\Controller\\CalendarEntryController::delete' => ['privates', '.service_locator.20D_ARC', 'get_ServiceLocator_20DARCService', true],
            'App\\Controller\\CalendarEntryController::edit' => ['privates', '.service_locator.20D_ARC', 'get_ServiceLocator_20DARCService', true],
            'App\\Controller\\CalendarEntryController::index' => ['privates', '.service_locator.YthCOdH', 'get_ServiceLocator_YthCOdHService', true],
            'App\\Controller\\CalendarEntryController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CalendarEntryController::show' => ['privates', '.service_locator.2BrnKx3', 'get_ServiceLocator_2BrnKx3Service', true],
            'App\\Controller\\CommentController::delete' => ['privates', '.service_locator.sE8VhYE', 'get_ServiceLocator_SE8VhYEService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.bJ1yb7y', 'get_ServiceLocator_BJ1yb7yService', true],
            'App\\Controller\\DocumentController::delete' => ['privates', '.service_locator.laaXC88', 'get_ServiceLocator_LaaXC88Service', true],
            'App\\Controller\\DocumentController::edit' => ['privates', '.service_locator.laaXC88', 'get_ServiceLocator_LaaXC88Service', true],
            'App\\Controller\\DocumentController::index' => ['privates', '.service_locator.UCjRy9H', 'get_ServiceLocator_UCjRy9HService', true],
            'App\\Controller\\DocumentController::logs' => ['privates', '.service_locator.Q8RAY9A', 'get_ServiceLocator_Q8RAY9AService', true],
            'App\\Controller\\DocumentController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\DocumentController::show' => ['privates', '.service_locator.Q8RAY9A', 'get_ServiceLocator_Q8RAY9AService', true],
            'App\\Controller\\DocumentLogController::viewLogs' => ['privates', '.service_locator.Q8RAY9A', 'get_ServiceLocator_Q8RAY9AService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:editUser' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\AdminController:manage' => ['privates', '.service_locator.bYqs9Eo', 'get_ServiceLocator_BYqs9EoService', true],
            'App\\Controller\\AdminController:register' => ['privates', '.service_locator.t8346QO', 'get_ServiceLocator_T8346QOService', true],
            'App\\Controller\\AnnouncementController:delete' => ['privates', '.service_locator.q.wNFcx', 'get_ServiceLocator_Q_WNFcxService', true],
            'App\\Controller\\AnnouncementController:edit' => ['privates', '.service_locator.q.wNFcx', 'get_ServiceLocator_Q_WNFcxService', true],
            'App\\Controller\\AnnouncementController:index' => ['privates', '.service_locator.AiNvJdq', 'get_ServiceLocator_AiNvJdqService', true],
            'App\\Controller\\AnnouncementController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AnnouncementController:show' => ['privates', '.service_locator.Fmc9k7c', 'get_ServiceLocator_Fmc9k7cService', true],
            'App\\Controller\\CalendarEntryController:delete' => ['privates', '.service_locator.20D_ARC', 'get_ServiceLocator_20DARCService', true],
            'App\\Controller\\CalendarEntryController:edit' => ['privates', '.service_locator.20D_ARC', 'get_ServiceLocator_20DARCService', true],
            'App\\Controller\\CalendarEntryController:index' => ['privates', '.service_locator.YthCOdH', 'get_ServiceLocator_YthCOdHService', true],
            'App\\Controller\\CalendarEntryController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CalendarEntryController:show' => ['privates', '.service_locator.2BrnKx3', 'get_ServiceLocator_2BrnKx3Service', true],
            'App\\Controller\\CommentController:delete' => ['privates', '.service_locator.sE8VhYE', 'get_ServiceLocator_SE8VhYEService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.bJ1yb7y', 'get_ServiceLocator_BJ1yb7yService', true],
            'App\\Controller\\DocumentController:delete' => ['privates', '.service_locator.laaXC88', 'get_ServiceLocator_LaaXC88Service', true],
            'App\\Controller\\DocumentController:edit' => ['privates', '.service_locator.laaXC88', 'get_ServiceLocator_LaaXC88Service', true],
            'App\\Controller\\DocumentController:index' => ['privates', '.service_locator.UCjRy9H', 'get_ServiceLocator_UCjRy9HService', true],
            'App\\Controller\\DocumentController:logs' => ['privates', '.service_locator.Q8RAY9A', 'get_ServiceLocator_Q8RAY9AService', true],
            'App\\Controller\\DocumentController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\DocumentController:show' => ['privates', '.service_locator.Q8RAY9A', 'get_ServiceLocator_Q8RAY9AService', true],
            'App\\Controller\\DocumentLogController:viewLogs' => ['privates', '.service_locator.Q8RAY9A', 'get_ServiceLocator_Q8RAY9AService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::editUser' => '?',
            'App\\Controller\\AdminController::manage' => '?',
            'App\\Controller\\AdminController::register' => '?',
            'App\\Controller\\AnnouncementController::delete' => '?',
            'App\\Controller\\AnnouncementController::edit' => '?',
            'App\\Controller\\AnnouncementController::index' => '?',
            'App\\Controller\\AnnouncementController::new' => '?',
            'App\\Controller\\AnnouncementController::show' => '?',
            'App\\Controller\\CalendarEntryController::delete' => '?',
            'App\\Controller\\CalendarEntryController::edit' => '?',
            'App\\Controller\\CalendarEntryController::index' => '?',
            'App\\Controller\\CalendarEntryController::new' => '?',
            'App\\Controller\\CalendarEntryController::show' => '?',
            'App\\Controller\\CommentController::delete' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\DocumentController::delete' => '?',
            'App\\Controller\\DocumentController::edit' => '?',
            'App\\Controller\\DocumentController::index' => '?',
            'App\\Controller\\DocumentController::logs' => '?',
            'App\\Controller\\DocumentController::new' => '?',
            'App\\Controller\\DocumentController::show' => '?',
            'App\\Controller\\DocumentLogController::viewLogs' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:editUser' => '?',
            'App\\Controller\\AdminController:manage' => '?',
            'App\\Controller\\AdminController:register' => '?',
            'App\\Controller\\AnnouncementController:delete' => '?',
            'App\\Controller\\AnnouncementController:edit' => '?',
            'App\\Controller\\AnnouncementController:index' => '?',
            'App\\Controller\\AnnouncementController:new' => '?',
            'App\\Controller\\AnnouncementController:show' => '?',
            'App\\Controller\\CalendarEntryController:delete' => '?',
            'App\\Controller\\CalendarEntryController:edit' => '?',
            'App\\Controller\\CalendarEntryController:index' => '?',
            'App\\Controller\\CalendarEntryController:new' => '?',
            'App\\Controller\\CalendarEntryController:show' => '?',
            'App\\Controller\\CommentController:delete' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\DocumentController:delete' => '?',
            'App\\Controller\\DocumentController:edit' => '?',
            'App\\Controller\\DocumentController:index' => '?',
            'App\\Controller\\DocumentController:logs' => '?',
            'App\\Controller\\DocumentController:new' => '?',
            'App\\Controller\\DocumentController:show' => '?',
            'App\\Controller\\DocumentLogController:viewLogs' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
