<?php

namespace ContainerYXB2xY0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBirthdayAnnouncementsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\BirthdayAnnouncementsCommand' shared autowired service.
     *
     * @return \App\Command\BirthdayAnnouncementsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'BirthdayAnnouncementsCommand.php';

        $container->privates['App\\Command\\BirthdayAnnouncementsCommand'] = $instance = new \App\Command\BirthdayAnnouncementsCommand(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:birthday-announcements');
        $instance->setDescription('Create an announcement for each user whose birthday is today');

        return $instance;
    }
}
