<?php

namespace ContainerOnVtZ1c;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DcmMJrxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dcmMJrx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dcmMJrx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'announcement' => ['privates', '.errored..service_locator.dcmMJrx.App\\Entity\\Announcement', NULL, 'Cannot autowire service ".service_locator.dcmMJrx": it needs an instance of "App\\Entity\\Announcement" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'announcement' => 'App\\Entity\\Announcement',
            'em' => '?',
        ]);
    }
}
