<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYXB2xY0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYXB2xY0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYXB2xY0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYXB2xY0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYXB2xY0\App_KernelDevDebugContainer([
    'container.build_hash' => 'YXB2xY0',
    'container.build_id' => 'd2380d5c',
    'container.build_time' => 1748948717,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYXB2xY0');
