<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOSYt0t5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOSYt0t5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOSYt0t5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOSYt0t5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOSYt0t5\App_KernelDevDebugContainer([
    'container.build_hash' => 'OSYt0t5',
    'container.build_id' => 'd159f05d',
    'container.build_time' => 1749341992,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOSYt0t5');
